resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: {machineset.machine.openshift.io
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      group: machine.openshift.io
      kind: MachineSet
      name: placeholder-name 


