apiVersion: v1
kind: Service
metadata:
  name: foo
  namespace: openshift-ingress
spec:
  ports:
  - name: 8443-tcp
    nodePort: 30327 
    port: 8443
    protocol: TCP
    targetPort: 8443
  sessionAffinity: None
  type: NodePort
